<?php
#CMS - CMS Made Simple
#(c)2004 by Ted Kulp (wishy@users.sf.net)
#This project's homepage is: http://cmsmadesimple.sf.net
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

$starttime = microtime();

@ob_start();

function microtime_diff($a, $b) {
	list($a_dec, $a_sec) = explode(" ", $a);
	list($b_dec, $b_sec) = explode(" ", $b);
	return $b_sec - $a_sec + $b_dec - $a_dec;
}

function ErrorHandler404($errno, $errmsg, $filename, $linenum, $vars)
{
	if ($errno == E_USER_WARNING) {
		@ob_end_clean();
		header("HTTP/1.0 404 Not Found");
		echo '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>';
		exit();
	}
}

require_once("include.php");

$smarty = new Smarty_ModuleInterface($config);

$modulecmsobj->page = $_GET["return_id"].$_POST["return_id"];
$smarty->page = $_GET["return_id"].$_POST["return_id"];
$smarty->module = $_GET["module"].$_POST["module"];
$smarty->id = $_GET["id"].$_POST["id"];

$params = array_merge($_GET, $_POST);
$smarty->params = $params;

$old_error_handler = set_error_handler("ErrorHandler404");
$html = $smarty->fetch('module:'.$modulecmsobj->page) . "\n";
set_error_handler($old_error_handler);

echo $html;

$endtime = microtime();

echo "<!-- Generated in ".microtime_diff($starttime,$endtime)." seconds by CMS Made Simple (not cached)-->\n";
echo "<!-- Generated by CMS Made Simple -- Released under the GPL -- http://cmsmadesimple.org -->\n";

@ob_flush();

# vim:ts=4 sw=4 noet
?>
