<?php

function usersInGroup($arg)
{
    global $db;
    $userid = get_userid();
    $access = check_permission($userid, 'Modify Group Assignments');

	// Instantiate the xajaxResponse object
	$objResponse = new xajaxResponse();

    $members = array();
    $nonmembers = array();
    if (! is_numeric($arg) || ! $access)
        {
        $arg = -1;
        }
    if ($arg != -1)
        {
	    $query = "SELECT u.user_id, u.username, ug.group_id FROM ".cms_db_prefix()."users u LEFT JOIN ".
            cms_db_prefix()."user_groups ug ON u.user_id = ug.user_id and group_id = ? ORDER BY u.username";
        $result = $db->Execute($query,array($arg));
        while($result && $row = $result->FetchRow())
            {
            if (isset($row['group_id']))
                {
                $members[$row['user_id']] = $row['username'];
                }
            else
                {
                $nonmembers[$row['user_id']] = $row['username'];
                }
            }

       $disp = '<div class="ajaxselection"><div style="float:left;"><p class="pagesubtitle">Members</p>';
       $disp .= '<ul class="sortable" id="members">';
       foreach ($members as $key=>$val)
            {
            $disp .= '<li id="members_members'.$key.'">';
            $disp .= $val.'</li>';
            }
       $disp .= "</ul></div>";
       $disp .= '<div style="float:left;"><p class="pagesubtitle">Nonmembers</p>';
       $disp .= '<ul class="sortable" id="nonmembers">';
       foreach ($nonmembers as $key=>$val)
            {
            $disp .= '<li id="nonmembers_nonmembers'.$key.'">'.$val.'</li>';
            }
       $disp .= "</ul></div>";
       $disp .= "</div>";
       $disp .= '<div class="ajaxbutton"><input type="button" value="Add All" onclick="xajax_addAll(1,'.$arg.');" />';
       $disp .= '&nbsp;<input type="button" value="Remove All" onclick="xajax_addAll(0,'.$arg.');" />';
       $disp .= '</div>';

	   // add a command to the response to assign the innerHTML attribute of
	   // the element with id="SomeElementId" to whatever the new content is
        $objResponse->addAssign("ajaxarea","innerHTML", $disp);
        $objResponse->addScript('function addMember() {xajax_saveChange('.$arg.', Sortable.serialize(\'members\'));}');
        $objResponse->addScript('Sortable.create(\'members\',{dropOnEmpty:true,constraint:false,containment:[\'members\',\'nonmembers\'],onUpdate:addMember});'); 
        $objResponse->addScript('Sortable.create(\'nonmembers\',{dropOnEmpty:true,constraint:false,containment:[\'members\',\'nonmembers\']});'); 
        $objResponse->addScript('var item=document.getElementById(\'ajaxarea\'); if (item) { item.style.visibility = \'visible\';}');
        }

	//return the XML response generated by the xajaxResponse object
	return $objResponse->getXML();

}

function addAll($op,$gid)
{
    global $db;

    $userid = get_userid();
    $access = check_permission($userid, 'Modify Group Assignments');
    if (! $access)
        {
        return;
        }
    // we remove all users from specified group before adding them (to prevent
    // duplicates)
    if ($op == 0 || $op == 1)
        {
        $query = "DELETE FROM ".cms_db_prefix()."user_groups WHERE group_id = ?";
        $result = $db->Execute($query,array($gid));
        }
    if ($op == 1)
        {
        // add all users into group gid
        $userlist = UserOperations::LoadUsers();
        foreach ($userlist as $thisUser)
            {
            $query = "INSERT INTO ".cms_db_prefix().
                "user_groups (group_id, user_id, create_date, modified_date) VALUES (".
                $db->qstr($gid).", ".$db->qstr($thisUser->id).", '".
                $db->DBTimeStamp(time())."', '".$db->DBTimeStamp(time())."')";
            $result = $db->Execute($query);
            }
        }
    audit($gid, 'Group ID', 'Changed Group Assignments');
	return usersInGroup($gid);
}


function saveChange($gid,$arg)
{
    global $db;
	$objResponse = new xajaxResponse();

    $userid = get_userid();
    $access = check_permission($userid, 'Modify Group Assignments');
    if (! $access)
        {
        return;
        }
	$query = "DELETE FROM ".cms_db_prefix()."user_groups WHERE group_id = ?";
    $result = $db->Execute($query,array($gid));
    $matches = array();
    preg_match_all( '/members(\d+)/', $arg, $matches);
    foreach ($matches[1] as $thisOne)
        {
          $query = "INSERT INTO ".cms_db_prefix()."user_groups (group_id, user_id, create_date, modified_date) VALUES (".
            $db->qstr($gid).", ".$db->qstr($thisOne).", '".$db->DBTimeStamp(time())."', '".$db->DBTimeStamp(time())."')";
          $result = $db->Execute($query);
        }

    audit($gid, 'Group ID', 'Changed Group Assignments');
	return $objResponse->getXML();

}


require_once(dirname(__FILE__)."/../include.php");
check_login();
$xajax = new xajax("ajax_changegroupassign.php");
$xajax->registerFunction("usersInGroup");
$xajax->registerFunction("saveChange");
$xajax->registerFunction("addAll");
$xajax->processRequests();
//debug_display($db);
?>