<?php

function permsForGroup($arg)
{
    global $db;
    $userid = get_userid();
    $access = check_permission($userid, 'Modify Permissions');

	// Instantiate the xajaxResponse object
	$objResponse = new xajaxResponse();

    $permitted = array();
    $forbidden = array();
    if (! is_numeric($arg) || ! $access)
        {
        $arg = -1;
        }
    if ($arg != -1)
        {
	    $query = "SELECT p.permission_id, p.permission_text, up.group_id FROM ".cms_db_prefix()."permissions p LEFT JOIN ".
            cms_db_prefix()."group_perms up ON p.permission_id = up.permission_id and group_id = ? ORDER BY p.permission_name";
        $result = $db->Execute($query,array($arg));
        while($result && $row = $result->FetchRow())
            {
            if (isset($row['group_id']))
                {
                $permitted[$row['permission_id']] = $row['permission_text'];
                }
            else
                {
                $forbidden[$row['permission_id']] = $row['permission_text'];
                }
            }

       $disp = '<div class="ajaxselection"><div style="float:left;"><p class="pagesubtitle">Permitted</p>';
       $disp .= '<ul class="sortable" id="permitted" MULTIPLE>';
       foreach ($permitted as $key=>$val)
            {
            $disp .= '<li id="permitted_permitted'.$key.'">';
            $disp .= $val.'</li>';
            }
       $disp .= "</ul></div>";
       $disp .= '<div style="float:left;"><p class="pagesubtitle">Forbidden</p>';
       $disp .= '<ul class="sortable" id="notpermitted" MULTIPLE>';
       foreach ($forbidden as $key=>$val)
            {
            $disp .= '<li id="notpermitted_notpermitted'.$key.'">'.$val.'</li>';
            }
       $disp .= "</ul></div>";
       $disp .= "</div>";
       $disp .= '<div class="ajaxbutton"><input type="button" value="Add All" onclick="xajax_addAll(1,'.$arg.');" />';
       $disp .= '&nbsp;<input type="button" value="Remove All" onclick="xajax_addAll(0,'.$arg.');" />';
       $disp .= '</div>';

	   // add a command to the response to assign the innerHTML attribute of
	   // the element with id="SomeElementId" to whatever the new content is
        $objResponse->addAssign("ajaxarea","innerHTML", $disp);
        $objResponse->addScript('function addPermission() {xajax_saveChange('.$arg.', Sortable.serialize(\'permitted\'));}');
        $objResponse->addScript('Sortable.create(\'permitted\',{dropOnEmpty:true,containment:[\'permitted\',\'notpermitted\'],constraint:false,onUpdate:addPermission});');
        $objResponse->addScript('Sortable.create(\'notpermitted\',{dropOnEmpty:true,containment:[\'permitted\',\'notpermitted\'],constraint:false});');
        }

	//return the XML response generated by the xajaxResponse object
	return $objResponse->getXML();

}

function addAll($op,$gid)
{
    global $db;

    $userid = get_userid();
    $access = check_permission($userid, 'Modify Permissions');
    if (! $access)
        {
        return;
        }
    // we remove all users from specified group before adding them (to prevent
    // duplicates)
    if ($op == 0 || $op == 1)
        {
        $query = "DELETE FROM ".cms_db_prefix()."group_perms WHERE group_id = ?";
        $result = $db->Execute($query,array($gid));
        }
    if ($op == 1)
        {
        // add all permisions for group gid
        $query = "SELECT permission_id from ".cms_db_prefix()."permissions";
        $result = $db->Execute($query);
        $perms = array();
        while($result && $row = $result->FetchRow())
            {
            array_push($perms,$row['permission_id']);
            }
        foreach ($perms as $thisPerm)
            {
            $new_id = $db->GenID(cms_db_prefix()."group_perms_seq");
            $query = "INSERT INTO ".cms_db_prefix()."group_perms (group_perm_id, group_id, permission_id, create_date, modified_date) VALUES (".
                $new_id.", ".$db->qstr($gid).", ".$db->qstr($thisPerm).", '".$db->DBTimeStamp(time())."', '".$db->DBTimeStamp(time())."')";
            $result = $db->Execute($query);
            }
        }
    audit($gid, 'Group ID', 'Changed Group Permissions');
	return permsForGroup($gid);
}


function saveChange($gid,$arg)
{
    global $db;
	$objResponse = new xajaxResponse();

    $userid = get_userid();
    $access = check_permission($userid, 'Modify Permissions');
    if (! $access)
        {
        return;
        }
	$query = "DELETE FROM ".cms_db_prefix()."group_perms WHERE group_id = ?";
    $result = $db->Execute($query,array($gid));
    $matches = array();
    preg_match_all( '/permitted(\d+)/', $arg, $matches);
    foreach ($matches[1] as $thisOne)
        {
          $new_id = $db->GenID(cms_db_prefix()."group_perms_seq");
          $query = "INSERT INTO ".cms_db_prefix()."group_perms (group_perm_id, group_id, permission_id, create_date, modified_date) VALUES (".
            $new_id.", ".$db->qstr($gid).", ".$db->qstr($thisOne).", '".$db->DBTimeStamp(time())."', '".$db->DBTimeStamp(time())."')";
          $result = $db->Execute($query);
        }

    audit($gid, 'Group ID', 'Changed Group Permissions');
	return $objResponse->getXML();
}


require_once(dirname(__FILE__)."/../include.php");
check_login();
$xajax = new xajax("ajax_changegroupperm.php");
$xajax->registerFunction("permsForGroup");
$xajax->registerFunction("saveChange");
$xajax->registerFunction("addAll");
$xajax->processRequests();
//debug_display($db);
?>