#! /bin/bash

D="$(dirname $0)"
[ "$D" = "." ] && D="$(pwd)"

# for testing, use like 'ROOT=. ./INSTALL'
r="$ROOT"

install --owner=root --group=root --mode="a=rx,u+w" --directory $r/etc/subversion
install --owner=root --group=root --mode="a=r,u+w" $D/{README.txt,config,servers} $r/etc/subversion
